# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# [START build-offsite-payments-app.app-configuration]
name = "<App Name>"
client_id = "<API Client ID>"
# [END build-offsite-payments-app.app-configuration]
application_url = "https://example.com"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://app.example.com/api/auth/callback",
  "https://app.example.com/api/auth/oauth/callback",
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
include_config_on_deploy = true
