name: Sync main with upstream

on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Sync latest commits from upstream repo
      
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main_updates
        fetch-depth: 0

    - name: Setup git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main_updates
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: Shopify/shopify-app-template-remix
        target_branch_push_args: --force

    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}

    - name: Create pull request
      if: steps.sync.outputs.has_new_commits == 'true'
      run: gh pr create -B main -H main_updates --title 'Sync main with upstream' --body 'This is an automated PR that syncs the repo with its upstream main'
